# Define a imagem base
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . ./

# Restaura as dependências e publica o aplicativo
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Define a imagem de produção
FROM mcr.microsoft.com/dotnet/aspnet:7.0

# Define o diretório de trabalho para o aplicativo publicado
WORKDIR /app

# Copia os arquivos publicados para o contêiner
COPY --from=build-env /app/out .
# Define a porta que o aplicativo irá expor
EXPOSE 80

# Define o comando de inicialização do aplicativo
# ENTRYPOINT ["dotnet", "NomeDoSeuApp.dll"]

ENTRYPOINT ["dotnet", "./front.dll"]